# Generated by Django 5.1.2 on 2024-11-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
