# Generated by Django 5.1.4 on 2024-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField(null=True)),
                ('Imaage', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
