# Generated by Django 5.1.2 on 2024-12-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Time', models.IntegerField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
