# Generated by Django 5.1.4 on 2024-12-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Age', models.IntegerField(null=True)),
                ('Number', models.IntegerField(null=True)),
            ],
        ),
    ]
