# Generated by Django 5.1.4 on 2024-12-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suntv', '0002_coopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopen',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
