# Generated by Django 5.1.2 on 2024-11-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Employes',
        ),
    ]
