# Generated by Django 5.1.2 on 2024-11-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gpay', '0002_foods_delete_employes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='Place',
        ),
        migrations.AddField(
            model_name='foods',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
