# Generated by Django 5.1.2 on 2024-11-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gpay', '0003_remove_foods_place_foods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.IntegerField()),
                ('Product_name', models.CharField(max_length=40)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
